language: node_js
node_js:
  - "4"
  - "stable"
sudo: false
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter coveralls
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info
